version: '3.8'

services:
  frontend:
    build:
      context: ./dans_fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  backend:
    build:
      context: ./dans_be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - JWT_SECRET=your-secret-key-dev
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: